CREATE TABLE news (
  ID SERIAL PRIMARY KEY,
  mood VARCHAR(255) NOT NULL,
  stamp VARCHAR(255) NOT NULL,
  country VARCHAR(255) NOT NULL,
  source VARCHAR(255) NOT NULL,
  words VARCHAR(255) NOT NULL,
)